# Generated by Django 3.0.5 on 2020-04-20 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamburgers', '0003_hamburger_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamburger',
            name='ingredients',
            field=models.ManyToManyField(blank=True, null=True, related_name='ingredients', to='hamburgers.Ingredient'),
        ),
    ]
