# Generated by Django 3.0.5 on 2020-04-30 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hamburgers', '0004_auto_20200420_0308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hamburger',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='hamburger',
            old_name='image',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='hamburger',
            old_name='ingredients',
            new_name='ingredientes',
        ),
        migrations.RenameField(
            model_name='hamburger',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='hamburger',
            old_name='price',
            new_name='precio',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='name',
            new_name='nombre',
        ),
    ]
